---
# Installs and configures Nginx web server

# Load OS specific variables
- name: load OS specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- include: install.yml
  tags:
    - BARC_INSTALL
    - BARC_INSTALL_PACKAGES

- include: configure.yml
  tags:
    - BARC_CONFIGURE
    - BARC_CONFIGURE_PACKAGE

- include: configure-firewall.yml
  tags:
    - BARC_CONFIGURE
    - BARC_CONFIGURE_FIREWALL

- include: register-role.yml
  tags:
    - BARC_ROLE_REGISTRATION
